version: "3.9"

services:
  db:
    image: postgres:15
    container_name: survey_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: survey_bot
    depends_on:
      - db
    environment:
      TOKEN: "7196045219:AAFfbeIZQXKAb_cgAC2cnbdMY__L0Iakcrg"
      DATABASE_URL: "postgresql://postgres:IJgDkPQTgFQTJqTomCNezddMsHJJPDmm@postgres.railway.internal:5432/railway"
      ADMIN_ID: "1262207928"
    restart: always

volumes:
  postgres_data:
